# Generated by Django 5.2 on 2025-06-05 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('exercise', models.CharField(max_length=100, verbose_name='Упражнение')),
                ('weight', models.FloatField(verbose_name='Вес (кг)')),
                ('reps', models.IntegerField(verbose_name='Количество повторений')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Личный рекорд',
                'verbose_name_plural': 'Личные рекорды',
                'ordering': ['-date'],
            },
        ),
    ]
