# Generated by Django 5.2.2 on 2025-06-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время отхода ко сну')),
                ('end_time', models.TimeField(verbose_name='Время пробуждения')),
                ('duration', models.FloatField(verbose_name='Длительность (часы)')),
                ('quality', models.CharField(max_length=50, verbose_name='Качество сна')),
                ('interruptions', models.IntegerField(default=0, verbose_name='Количество пробуждений')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Сон',
                'verbose_name_plural': 'Сон',
                'ordering': ['-date'],
            },
        ),
    ]
