# Generated by Django 5.2 on 2025-05-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('meal_type', models.CharField(max_length=50, verbose_name='Тип приема пищи')),
                ('calories', models.IntegerField(verbose_name='Калории')),
                ('protein', models.FloatField(verbose_name='Белки (г)')),
                ('fat', models.FloatField(verbose_name='Жиры (г)')),
                ('carbs', models.FloatField(verbose_name='Углеводы (г)')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Прием пищи',
                'verbose_name_plural': 'Питание',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
