# Generated by Django 5.2 on 2025-06-05 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_alter_meal_meal_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyNutritionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Начало недели')),
                ('week_end', models.DateField(verbose_name='Конец недели')),
                ('total_calories', models.IntegerField(default=0, verbose_name='Всего калорий')),
                ('avg_daily_calories', models.FloatField(default=0, verbose_name='Среднее калорий в день')),
                ('total_protein', models.FloatField(default=0, verbose_name='Всего белков (г)')),
                ('total_fat', models.FloatField(default=0, verbose_name='Всего жиров (г)')),
                ('total_carbs', models.FloatField(default=0, verbose_name='Всего углеводов (г)')),
                ('breakfast_count', models.IntegerField(default=0, verbose_name='Количество завтраков')),
                ('lunch_count', models.IntegerField(default=0, verbose_name='Количество обедов')),
                ('snack_count', models.IntegerField(default=0, verbose_name='Количество перекусов')),
                ('dinner_count', models.IntegerField(default=0, verbose_name='Количество ужинов')),
                ('avg_breakfast_calories', models.FloatField(default=0, verbose_name='Среднее калорий на завтрак')),
                ('avg_lunch_calories', models.FloatField(default=0, verbose_name='Среднее калорий на обед')),
                ('avg_snack_calories', models.FloatField(default=0, verbose_name='Среднее калорий на перекус')),
                ('avg_dinner_calories', models.FloatField(default=0, verbose_name='Среднее калорий на ужин')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Недельная статистика питания',
                'verbose_name_plural': 'Недельная статистика питания',
                'ordering': ['-week_start'],
                'unique_together': {('user', 'week_start')},
            },
        ),
    ]
