# Generated by Django 5.2 on 2025-06-05 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_weeklynutritionstats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyNutritionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('total_calories', models.IntegerField(default=0, verbose_name='Всего калорий')),
                ('avg_daily_calories', models.FloatField(default=0, verbose_name='Среднее калорий в день')),
                ('total_protein', models.FloatField(default=0, verbose_name='Всего белков (г)')),
                ('total_fat', models.FloatField(default=0, verbose_name='Всего жиров (г)')),
                ('total_carbs', models.FloatField(default=0, verbose_name='Всего углеводов (г)')),
                ('breakfast_count', models.IntegerField(default=0, verbose_name='Количество завтраков')),
                ('lunch_count', models.IntegerField(default=0, verbose_name='Количество обедов')),
                ('snack_count', models.IntegerField(default=0, verbose_name='Количество перекусов')),
                ('dinner_count', models.IntegerField(default=0, verbose_name='Количество ужинов')),
                ('avg_breakfast_calories', models.FloatField(default=0, verbose_name='Среднее калорий на завтрак')),
                ('avg_lunch_calories', models.FloatField(default=0, verbose_name='Среднее калорий на обед')),
                ('avg_snack_calories', models.FloatField(default=0, verbose_name='Среднее калорий на перекус')),
                ('avg_dinner_calories', models.FloatField(default=0, verbose_name='Среднее калорий на ужин')),
                ('days_tracked', models.IntegerField(default=0, verbose_name='Дней с записями')),
                ('most_common_meal_type', models.CharField(blank=True, max_length=50, verbose_name='Самый частый прием пищи')),
                ('highest_calorie_day', models.DateField(blank=True, null=True, verbose_name='День с максимальными калориями')),
                ('max_daily_calories', models.IntegerField(default=0, verbose_name='Максимум калорий за день')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Месячная статистика питания',
                'verbose_name_plural': 'Месячная статистика питания',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
