# Generated by Django 5.2.2 on 2025-06-05 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('calories_per_hour', models.IntegerField(verbose_name='Калории в час')),
            ],
            options={
                'verbose_name': 'Тип тренировки',
                'verbose_name_plural': 'Типы тренировок',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('duration', models.DurationField(verbose_name='Продолжительность')),
                ('intensity', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], default='medium', max_length=10, verbose_name='Интенсивность')),
                ('calories_burned', models.IntegerField(verbose_name='Сожжено калорий')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('workout_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workouttype', verbose_name='Тип тренировки')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
                'ordering': ['-date'],
            },
        ),
    ]
