# Generated by Django 5.2 on 2025-06-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_add_default_workout_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='calories_burned',
            field=models.IntegerField(editable=False, verbose_name='Сожжено калорий'),
        ),
    ]
