# Generated by Django 5.2 on 2025-06-05 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_workout_type'),
        ('workouts', '0003_alter_workout_calories_burned'),
    ]

    operations = [
    ]
